### ISSUE TITLE
[Vssue]Pomerium, Kubernetes Single Sign-on with OpenID Connect | LinuxBlog.xyz

### ISSUE THREAD

**Issue by Kerwood** [Kerwood/linuxblog-xyz#7]
https://linuxblog.xyz/posts/pomerium-kubernetes-single-sign-on/

**Comment by velann21** [comment]
Hey Keroo, Thanks for this nice blog about the promerium, unfortunately I am getting error while issuing commands like kubectl get po

Error is : error: the server doesn't have a resource type "pods"

**Comment by Kerwood** [comment]
Hmm that is a bit strange.
Could you give an example of what you have done?

**Comment by velann21** [comment]
@Kerwood

> Hmm that is a bit strange.
> Could you give an example of what you have done?

So actually, I am trying to set the github as IDP, apart from that, I have followed the exact steps you have mentioned in the blog.

https://github.com/velann21/pomerium-test/tree/master these are the yaml file

**Comment by Kerwood** [comment]
You deleted the repo :)

Should you not use the full github email in the role binding?
Why do you create the `cluster-admin` role ? It already exists.

You are missing the policy property, why is that ?
```
- from: https://echo.demo.velanwin.com
  to: https://kubernetes.default.svc
  tls_skip_verify: true
  allow_spdy: true
  allow_public_unauthenticated_access: true
  allowed_idp_claims:
    email:
    - your-mail@gmail.com
```
